version: "3"
services:
  api:
    build:
      context: ../
      dockerfile: ./containers/api/Dockerfile
      args:
        GIT_REVISION: ${GIT_REVISION}
    image: bbengfort/epistolary-api
    init: true
    depends_on:
      - postgres
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      - EPISTOLARY_MAINTENANCE=false
      - EPISTOLARY_BIND_ADDR=:8000
      - EPISTOLARY_MODE=debug
      - EPISTOLARY_LOG_LEVEL=info
      - EPISTOLARY_CONSOLE_LOG=true
      - EPISTOLARY_ALLOW_ORIGINS=http://localhost:3000
      - EPISTOLARY_DATABASE_URL=postgres://postgres:postgres@postgres:5432/epistolary?sslmode=disable
      - EPISTOLARY_DATABASE_READ_ONLY=false
      - EPISTOLARY_TOKEN_KEYS=01GE6191AQTGMCJ9BN0QC3CCVG:run/secrets/01GE6191AQTGMCJ9BN0QC3CCVG.pem,01GE62EXXR0X0561XD53RDFBQJ:run/secrets/01GE62EXXR0X0561XD53RDFBQJ.pem
      - EPISTOLARY_TOKEN_AUDIENCE=http://localhost:3000
      - EPISTOLARY_TOKEN_ISSUER=http://localhost:8000
      - EPISTOLARY_SENTRY_DSN=${EPISTOLARY_SENTRY_DSN}
      - EPISTOLARY_SENTRY_SERVER_NAME=docker
      - EPISTOLARY_SENTRY_ENVIRONMENT=development
      - EPISTOLARY_SENTRY_TRACK_PERFORMANCE=true
      - EPISTOLARY_SENTRY_SAMPLE_RATE=0.95
    secrets:
      - 01GE6191AQTGMCJ9BN0QC3CCVG.pem
      - 01GE62EXXR0X0561XD53RDFBQJ.pem

  web:
    build:
      context: ../
      dockerfile: ./containers/web/Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost:8000/
        REACT_APP_ANALYTICS_ID: ${REACT_APP_ANALYTICS_ID}
        REACT_APP_VERSION_NUMBER: v0.3.0-dev
        REACT_APP_GIT_REVISION: ${GIT_REVISION}
        REACT_APP_SENTRY_DSN: ${REACT_APP_SENTRY_DSN}
        REACT_APP_SENTRY_ENVIRONMENT: development
        REACT_APP_USE_DASH_LOCALE: "true"
    image: bbengfort/epistolary-web
    init: true
    depends_on:
      - api
    ports:
      - 3000:80

  postgres:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/db
      - "./pkg/server/db/migrations/000001_initial_schema.up.sql:/docker-entrypoint-initdb.d/000001_initial_schema.up.sql"
      - "./pkg/server/db/migrations/000002_default_roles.up.sql:/docker-entrypoint-initdb.d/000002_default_roles.up.sql"
      - "./postgres/999999_schema_version.up.sql:/docker-entrypoint-initdb.d/999999_schema_version.up.sql"
    init: true
    restart: always
    ports:
      - 50432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=epistolary

volumes:
  pgdata:

secrets:
  01GE62EXXR0X0561XD53RDFBQJ.pem:
    file: ./api/fixtures/01GE62EXXR0X0561XD53RDFBQJ.pem
  01GE6191AQTGMCJ9BN0QC3CCVG.pem:
    file: ./api/fixtures/01GE6191AQTGMCJ9BN0QC3CCVG.pem