name: Containers
on:
  push:
    branches:
      - main
    tags:
      - "v*"

# Each container image is built in its own job. To add an image, simply copy and paste
# one of the jobs and configure the build to point to the container's Dockerfile and
# tags. If the build is main or for a tag then the images are pushed to dockerhub and
# gcr; images are not pushed on pull requests.
jobs:
  # Epistolary API
  api:
    name: API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment
        id: vars
        run: |
          echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
          echo "::set-output name=revision::$(git rev-parse --short HEAD)"

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as basenames for tags
          # this should be configured for each container built
          images: |
            bbengfort/epistolary-api
          tags: |
            type=semver,pattern={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=,suffix=,format=short

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # context and Dockerfile - should be configured for each image
          context: .
          file: ./containers/api/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_REVISION=${{ steps.vars.outputs.revision }}

  # Epistolary UI: epistolary.app
  web:
    name: Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment
        id: vars
        run: |
          echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
          echo "::set-output name=revision::$(git rev-parse --short HEAD)"

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as basenames for tags
          # this should be configured for each container built
          images: |
            bbengfort/epistolary-web
          tags: |
            type=semver,pattern={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=,suffix=,format=short

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # context and Dockerfile - should be configured for each image
          context: .
          file: ./containers/web/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            REACT_APP_API_BASE_URL=https://api.epistolary.app/v1/
            REACT_APP_ANALYTICS_ID=${{ secrets.REACT_APP_ANALYTICS_ID }}
            REACT_APP_VERSION_NUMBER=${{ steps.vars.outputs.tag }}
            REACT_APP_GIT_REVISION=${{ steps.vars.outputs.revision }}
            REACT_APP_SENTRY_DSN=${{ secrets.REACT_APP_SENTRY_DSN }}
            REACT_APP_SENTRY_ENVIRONMENT=production
            REACT_APP_USE_DASH_LOCALE=false