name: CI
on:
  push:
    branches:
      - main
      - "v*"
    tags:
      - "v*"
  pull_request:

jobs:
  lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.3.3

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Go Code
        run: staticcheck ./...

  test:
    name: Go Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go-version: [1.18.x, 1.19.x]
    env:
      GOPATH: ${{ github.workspace }}/go
      GOBIN: ${{ github.workspace }}/go/bin
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/bbengfort/epistolary
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Speedup
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: ${{ env.GOPATH }}/src/github.com/bbengfort/epistolary

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"

      - name: Install Dependencies
        run: |
          go version
          go install github.com/kevinburke/go-bindata/go-bindata@v3.24.0

      - name: Code Generation
        run: go generate ./...

      - name: Run Unit Tests
        run: go test -v -coverprofile=coverage.txt -covermode=atomic --race ./...

  build:
    name: Go Build
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/go
      GOBIN: ${{ github.workspace }}/go/bin
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/bbengfort/epistolary
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Cache Speedup
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: ${{ env.GOPATH }}/src/github.com/bbengfort/epistolary

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"

      - name: Install Dependencies
        run: |
          go version
          go install github.com/kevinburke/go-bindata/go-bindata@v3.24.0

      - name: Code Generation
        run: go generate ./...

      - name: Build
        run: go build ./cmd/...

  yarn:
    name: Yarn Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.7.0
          cache: "yarn"
          cache-dependency-path: ./web/yarn.lock

      - name: Install Dependencies
        working-directory: ./web
        run: yarn

      - name: Run Tests
        working-directory: ./web
        env:
          REACT_APP_API_BASE_URL: http://localhost:8000/v1/
        run: yarn test

